# Generated by Django 3.1.2 on 2020-10-27 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_cregeval_bi', '0001_initial'),
        ('login_cregeval_bi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cregevaluser',
            name='privilegio_user',
            field=models.ForeignKey(help_text='Designe entre los privilegios existentes, el que sea requerido para el usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_cregeval_bi.cregevalcasttype', verbose_name='Privilegio asignado'),
        ),
    ]
