# Generated by Django 3.1.2 on 2020-10-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_cregeval_bi', '0002_cregevaluser_privilegio_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cregevaluser',
            options={'verbose_name': 'Usuario'},
        ),
    ]
