# Generated by Django 3.1.2 on 2020-10-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CregevalCastType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilegio', models.CharField(help_text='En este campo se colocará el nombre del rango existente en el portal', max_length=100, unique=True, verbose_name='Nombre del cargo o privilegio')),
            ],
            options={
                'verbose_name': 'Privilegio',
            },
        ),
    ]
