# Generated by Django 3.1.2 on 2020-11-03 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='Indique el nombre de la entidad a la que se le presta el servicio de informes', max_length=100, unique=True, verbose_name='Nombre de la companía')),
                ('nit', models.IntegerField(help_text='Proporcione el Número Identificador Tributario designado para la entidad', null=True, unique=True, verbose_name='NIT de la entidad')),
                ('bi_link', models.CharField(help_text='Indique el vinculo para compartir el informe de Power BI. Este vinculo se puede encontrar en el portal web de Power BI dentro del informe, usando el botón de "Compartir", seleccoionando la sección de "Insertar informe" y haciendo click nuevamente en el botón "Publicar en la web".', max_length=255, null=True, verbose_name='Vínculo del informe Power BI')),
                ('logo', models.ImageField(default=None, help_text='Asigue el logo de su compañía para la identidad del sitio (preferiblemente en formato .PNG o en .SVG para mayor calidad de imagen).', upload_to='', verbose_name='Logo de la compañía')),
                ('slide1_title', models.CharField(default=None, help_text='Indique el titulo del slide 1 del carrusel que se encuentra en la pantalla principal', max_length=50, verbose_name='Titulo del slide 1 del carrrusel')),
                ('slide2_title', models.CharField(default=None, help_text='Indique el titulo del slide 2 del carrusel que se encuentra en la pantalla principal', max_length=50, verbose_name='Titulo del slide 2 del carrrusel')),
                ('slide3_title', models.CharField(default=None, help_text='Indique el titulo del slide 3 del carrusel que se encuentra en la pantalla principal', max_length=50, verbose_name='Titulo del slide 3 del carrrusel')),
                ('slide1_content', models.TextField(default=None, help_text='Indique el contenido de texto del slide 1 del carrusel que se encuentra en la pantalla principal', max_length=400, verbose_name='Contenido del slide 1 del carrrusel')),
                ('slide2_content', models.TextField(default=None, help_text='Indique el contenido de texto del slide 2 del carrusel que se encuentra en la pantalla principal', max_length=400, verbose_name='Contenido del slide 2 del carrrusel')),
                ('slide3_content', models.TextField(default=None, help_text='Indique el contenido de texto del slide 3 del carrusel que se encuentra en la pantalla principal', max_length=400, verbose_name='Contenido del slide 3 del carrrusel')),
                ('details_maintitle', models.CharField(default=None, help_text='Indique el titulo general de la sección de detalles', max_length=50, verbose_name='Titulo principal de la sección de detalles')),
                ('details_detail', models.TextField(default=None, help_text='Indique la descripción general de la sección de detalles', max_length=200, verbose_name='Descripción de la sección de detalles')),
                ('detail1_title', models.CharField(default=None, help_text='Indique el titulo del slide 1 del carrusel que se encuentra en la pantalla principal', max_length=50, verbose_name='Titulo del slide 1 del carrrusel')),
                ('detail2_title', models.CharField(default=None, help_text='Indique el titulo del slide 2 del carrusel que se encuentra en la pantalla principal', max_length=50, verbose_name='Titulo del slide 2 del carrrusel')),
                ('detail3_title', models.CharField(default=None, help_text='Indique el titulo del slide 3 del carrusel que se encuentra en la pantalla principal', max_length=50, verbose_name='Titulo del slide 3 del carrrusel')),
                ('detail1_content', models.TextField(default=None, help_text='Indique el contenido de texto del slide 1 del carrusel que se encuentra en la pantalla principal', max_length=400, verbose_name='Contenido del slide 1 del carrrusel')),
                ('detail2_content', models.TextField(default=None, help_text='Indique el contenido de texto del slide 2 del carrusel que se encuentra en la pantalla principal', max_length=400, verbose_name='Contenido del slide 2 del carrrusel')),
                ('detail3_content', models.TextField(default=None, help_text='Indique el contenido de texto del slide 3 del carrusel que se encuentra en la pantalla principal', max_length=400, verbose_name='Contenido del slide 3 del carrrusel')),
                ('cliente', models.OneToOneField(default=None, help_text='Asigne el cliente dueño de el contenido actual', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente propietario')),
            ],
            options={
                'verbose_name': 'Compañía',
            },
        ),
    ]
