# Generated by Django 3.1.2 on 2020-11-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_cregeval_bi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontent',
            name='detail1_content',
            field=models.TextField(help_text='Indique el contenido de texto del slide 1 del carrusel que se encuentra en la pantalla principal', max_length=400, null=True, verbose_name='Contenido del slide 1 del carrrusel'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='detail1_title',
            field=models.CharField(help_text='Indique el titulo del slide 1 del carrusel que se encuentra en la pantalla principal', max_length=50, null=True, verbose_name='Titulo del slide 1 del carrrusel'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='detail2_content',
            field=models.TextField(help_text='Indique el contenido de texto del slide 2 del carrusel que se encuentra en la pantalla principal', max_length=400, null=True, verbose_name='Contenido del slide 2 del carrrusel'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='detail2_title',
            field=models.CharField(help_text='Indique el titulo del slide 2 del carrusel que se encuentra en la pantalla principal', max_length=50, null=True, verbose_name='Titulo del slide 2 del carrrusel'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='detail3_content',
            field=models.TextField(help_text='Indique el contenido de texto del slide 3 del carrusel que se encuentra en la pantalla principal', max_length=400, null=True, verbose_name='Contenido del slide 3 del carrrusel'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='detail3_title',
            field=models.CharField(help_text='Indique el titulo del slide 3 del carrusel que se encuentra en la pantalla principal', max_length=50, null=True, verbose_name='Titulo del slide 3 del carrrusel'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='details_detail',
            field=models.TextField(help_text='Indique la descripción general de la sección de detalles', max_length=200, null=True, verbose_name='Descripción de la sección de detalles'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='details_maintitle',
            field=models.CharField(help_text='Indique el titulo general de la sección de detalles', max_length=50, null=True, verbose_name='Titulo principal de la sección de detalles'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='logo',
            field=models.ImageField(help_text='Asigue el logo de su compañía para la identidad del sitio (preferiblemente en formato .PNG o en .SVG para mayor calidad de imagen).', null=True, upload_to='', verbose_name='Logo de la compañía'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='name',
            field=models.CharField(default='Compañía', help_text='Indique el nombre de la entidad a la que se le presta el servicio de informes', max_length=100, unique=True, verbose_name='Nombre de la companía'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='slide1_content',
            field=models.TextField(help_text='Indique el contenido de texto del slide 1 del carrusel que se encuentra en la pantalla principal', max_length=400, null=True, verbose_name='Contenido del slide 1 del carrrusel'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='slide1_title',
            field=models.CharField(help_text='Indique el titulo del slide 1 del carrusel que se encuentra en la pantalla principal', max_length=50, null=True, verbose_name='Titulo del slide 1 del carrrusel'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='slide2_content',
            field=models.TextField(help_text='Indique el contenido de texto del slide 2 del carrusel que se encuentra en la pantalla principal', max_length=400, null=True, verbose_name='Contenido del slide 2 del carrrusel'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='slide2_title',
            field=models.CharField(help_text='Indique el titulo del slide 2 del carrusel que se encuentra en la pantalla principal', max_length=50, null=True, verbose_name='Titulo del slide 2 del carrrusel'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='slide3_content',
            field=models.TextField(help_text='Indique el contenido de texto del slide 3 del carrusel que se encuentra en la pantalla principal', max_length=400, null=True, verbose_name='Contenido del slide 3 del carrrusel'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='slide3_title',
            field=models.CharField(help_text='Indique el titulo del slide 3 del carrusel que se encuentra en la pantalla principal', max_length=50, null=True, verbose_name='Titulo del slide 3 del carrrusel'),
        ),
    ]
