# Generated by Django 3.1.2 on 2020-11-03 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_cregeval_bi', '0002_auto_20201103_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontent',
            name='cliente',
            field=models.OneToOneField(help_text='Asigne el cliente dueño de el contenido actual', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente propietario'),
        ),
    ]
