# Generated by Django 3.1.2 on 2020-11-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_cregeval_bi', '0006_auto_20201103_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontent',
            name='slide1_img',
            field=models.ImageField(help_text='Inserte la imagen de fondo del slide 1 de la presentación de su cliente.', null=True, upload_to='', verbose_name='Imagen de slide 1'),
        ),
        migrations.AddField(
            model_name='companycontent',
            name='slide2_img',
            field=models.ImageField(help_text='Inserte la imagen de fondo del slide 2 de la presentación de su cliente.', null=True, upload_to='', verbose_name='Imagen de slide 2'),
        ),
        migrations.AddField(
            model_name='companycontent',
            name='slide3_img',
            field=models.ImageField(help_text='Inserte la imagen de fondo del slide 3 de la presentación de su cliente.', null=True, upload_to='', verbose_name='Imagen de slide 3'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='detail1_content',
            field=models.TextField(help_text='Indique el contenido del primer elemento de detalles que se encuentra en la pantalla principal', max_length=400, null=True, verbose_name='Contenido del primer elemento de detalles'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='detail1_title',
            field=models.CharField(help_text='Indique el titulo del primer elemento de detalles que se encuentra en la pantalla principal', max_length=50, null=True, verbose_name='Titulo del primer elemento de detalles'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='detail2_content',
            field=models.TextField(help_text='Indique el contenido del segundo elemento de detalles que se encuentra en la pantalla principal', max_length=400, null=True, verbose_name='Contenido del segundo elemento de detalles'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='detail2_title',
            field=models.CharField(help_text='Indique el titulo del segundo elemento de detalles que se encuentra en la pantalla principal', max_length=50, null=True, verbose_name='Titulo del segundo elemento de detalles'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='detail3_content',
            field=models.TextField(help_text='Indique el contenido del tercer elemento de detalles que se encuentra en la pantalla principal', max_length=400, null=True, verbose_name='Contenido del tercer elemento de detalles'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='detail3_title',
            field=models.CharField(help_text='Indique el titulo del tercer elemento de detalles que se encuentra en la pantalla principal', max_length=50, null=True, verbose_name='Titulo del tercer elemento de detalles'),
        ),
        migrations.AlterField(
            model_name='companycontent',
            name='logo',
            field=models.ImageField(help_text='Asigne el logo de su compañía para la identidad del sitio (preferiblemente en formato .PNG o en .SVG para mayor calidad de imagen).', null=True, upload_to='', verbose_name='Logo de la compañía'),
        ),
    ]
